kind: Service
apiVersion: v1
metadata:
  name: api-gateway
  namespace: default
  labels:
    app: api-gateway
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31902
  selector:
    app: api-gateway
  clusterIP: 10.97.54.136
  clusterIPs:
    - 10.97.54.136
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}
