kind: Service
apiVersion: v1
metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30243
  selector:
    app: mongo
  clusterIP: 10.105.32.218
  clusterIPs:
    - 10.105.32.218
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}
