# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\"\xd1\x01\n\x04\x42ook\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x13\n\x0bpreviewLink\x18\x06 \x01(\t\x12\x11\n\tpublisher\x18\x07 \x01(\t\x12\x15\n\rpublishedDate\x18\x08 \x01(\t\x12\x10\n\x08infoLink\x18\t \x01(\t\x12\x12\n\ncategories\x18\n \x01(\t\x12\x14\n\x0cratingsCount\x18\x0b \x01(\t\"\xc9\x01\n\x08\x42ookNoId\x12\r\n\x05Title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\t\x12\x13\n\x0bpreviewLink\x18\x05 \x01(\t\x12\x11\n\tpublisher\x18\x06 \x01(\t\x12\x15\n\rpublishedDate\x18\x07 \x01(\t\x12\x10\n\x08infoLink\x18\x08 \x01(\t\x12\x12\n\ncategories\x18\t \x01(\t\x12\x14\n\x0cratingsCount\x18\n \x01(\t\"\x1e\n\x0b\x42ookMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x0e\x41\x64\x64\x42ookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"!\n\x0eGetBookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"=\n\x11UpdateBookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x17\n\x04\x62ook\x18\x02 \x01(\x0b\x32\t.BookNoId\"$\n\x11\x44\x65leteBookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"&\n\x15GetBookByTitleRequest\x12\r\n\x05title\x18\x01 \x01(\t\")\n\x16GetBookByTitleResponse\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x32\xfd\x01\n\x0b\x42ookService\x12(\n\x07\x41\x64\x64\x42ook\x12\x0f.AddBookRequest\x1a\x0c.BookMessage\x12!\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x05.Book\x12.\n\nUpdateBook\x12\x12.UpdateBookRequest\x1a\x0c.BookMessage\x12.\n\nDeleteBook\x12\x12.DeleteBookRequest\x1a\x0c.BookMessage\x12\x41\n\x0eGetBookByTitle\x12\x16.GetBookByTitleRequest\x1a\x17.GetBookByTitleResponseb\x06proto3')



_BOOK = DESCRIPTOR.message_types_by_name['Book']
_BOOKNOID = DESCRIPTOR.message_types_by_name['BookNoId']
_BOOKMESSAGE = DESCRIPTOR.message_types_by_name['BookMessage']
_ADDBOOKREQUEST = DESCRIPTOR.message_types_by_name['AddBookRequest']
_GETBOOKREQUEST = DESCRIPTOR.message_types_by_name['GetBookRequest']
_UPDATEBOOKREQUEST = DESCRIPTOR.message_types_by_name['UpdateBookRequest']
_DELETEBOOKREQUEST = DESCRIPTOR.message_types_by_name['DeleteBookRequest']
_GETBOOKBYTITLEREQUEST = DESCRIPTOR.message_types_by_name['GetBookByTitleRequest']
_GETBOOKBYTITLERESPONSE = DESCRIPTOR.message_types_by_name['GetBookByTitleResponse']
Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:Book)
  })
_sym_db.RegisterMessage(Book)

BookNoId = _reflection.GeneratedProtocolMessageType('BookNoId', (_message.Message,), {
  'DESCRIPTOR' : _BOOKNOID,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:BookNoId)
  })
_sym_db.RegisterMessage(BookNoId)

BookMessage = _reflection.GeneratedProtocolMessageType('BookMessage', (_message.Message,), {
  'DESCRIPTOR' : _BOOKMESSAGE,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:BookMessage)
  })
_sym_db.RegisterMessage(BookMessage)

AddBookRequest = _reflection.GeneratedProtocolMessageType('AddBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKREQUEST,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:AddBookRequest)
  })
_sym_db.RegisterMessage(AddBookRequest)

GetBookRequest = _reflection.GeneratedProtocolMessageType('GetBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKREQUEST,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:GetBookRequest)
  })
_sym_db.RegisterMessage(GetBookRequest)

UpdateBookRequest = _reflection.GeneratedProtocolMessageType('UpdateBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEBOOKREQUEST,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:UpdateBookRequest)
  })
_sym_db.RegisterMessage(UpdateBookRequest)

DeleteBookRequest = _reflection.GeneratedProtocolMessageType('DeleteBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEBOOKREQUEST,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:DeleteBookRequest)
  })
_sym_db.RegisterMessage(DeleteBookRequest)

GetBookByTitleRequest = _reflection.GeneratedProtocolMessageType('GetBookByTitleRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKBYTITLEREQUEST,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:GetBookByTitleRequest)
  })
_sym_db.RegisterMessage(GetBookByTitleRequest)

GetBookByTitleResponse = _reflection.GeneratedProtocolMessageType('GetBookByTitleResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKBYTITLERESPONSE,
  '__module__' : 'books_pb2'
  # @@protoc_insertion_point(class_scope:GetBookByTitleResponse)
  })
_sym_db.RegisterMessage(GetBookByTitleResponse)

_BOOKSERVICE = DESCRIPTOR.services_by_name['BookService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=16
  _BOOK._serialized_end=225
  _BOOKNOID._serialized_start=228
  _BOOKNOID._serialized_end=429
  _BOOKMESSAGE._serialized_start=431
  _BOOKMESSAGE._serialized_end=461
  _ADDBOOKREQUEST._serialized_start=463
  _ADDBOOKREQUEST._serialized_end=500
  _GETBOOKREQUEST._serialized_start=502
  _GETBOOKREQUEST._serialized_end=535
  _UPDATEBOOKREQUEST._serialized_start=537
  _UPDATEBOOKREQUEST._serialized_end=598
  _DELETEBOOKREQUEST._serialized_start=600
  _DELETEBOOKREQUEST._serialized_end=636
  _GETBOOKBYTITLEREQUEST._serialized_start=638
  _GETBOOKBYTITLEREQUEST._serialized_end=676
  _GETBOOKBYTITLERESPONSE._serialized_start=678
  _GETBOOKBYTITLERESPONSE._serialized_end=719
  _BOOKSERVICE._serialized_start=722
  _BOOKSERVICE._serialized_end=975
# @@protoc_insertion_point(module_scope)
