apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    import time
    from locust import HttpUser, task

    class QuickstartUser(HttpUser):
        def on_start(self):
            self.client.post("/api/login/fdasf/gdss")  # Define the endpoint you want to hit during the load test
