scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'api-gateway'
      scrape_interval: 5s
      static_configs:
        - targets: ['10.97.54.136:9090']