# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"G\n\x04User\x12\n\n\x02Id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x04 \x01(\t\"3\n\rUpdateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1c\n\x0eUpdateResponse\x12\n\n\x02ok\x18\x01 \x01(\t\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t2\x9f\x01\n\x0bUserService\x12,\n\tUpdateKey\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12.\n\x0bVerifyToken\x12\x0e.VerifyRequest\x1a\x0f.UpdateResponse\x12\x32\n\x0fVerifyUserToken\x12\x0e.VerifyRequest\x1a\x0f.UpdateResponseb\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_UPDATEREQUEST = DESCRIPTOR.message_types_by_name['UpdateRequest']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['UpdateResponse']
_VERIFYREQUEST = DESCRIPTOR.message_types_by_name['VerifyRequest']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)

VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:VerifyRequest)
  })
_sym_db.RegisterMessage(VerifyRequest)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=15
  _USER._serialized_end=86
  _UPDATEREQUEST._serialized_start=88
  _UPDATEREQUEST._serialized_end=139
  _UPDATERESPONSE._serialized_start=141
  _UPDATERESPONSE._serialized_end=169
  _VERIFYREQUEST._serialized_start=171
  _VERIFYREQUEST._serialized_end=201
  _USERSERVICE._serialized_start=204
  _USERSERVICE._serialized_end=363
# @@protoc_insertion_point(module_scope)
