apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  clusterIP: 10.95.128.22
  clusterIPs:
    - 10.95.128.22
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: app
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prometeus