#apiVersion: v1
#kind: Service
#metadata:
#  name: books
#spec:
#  clusterIP: 10.95.128.55
#  clusterIPs:
#    - 10.95.128.55
#  selector:
#    app: books
#  ports:
#    - protocol: TCP
#      port: 50051
#      targetPort: 8080
#      name: app
#    - protocol: TCP
#      port: 9090
#      targetPort: 9090
#      name: prometeus


kind: Service
apiVersion: v1
metadata:
  name: books
  namespace: default
  labels:
    app: books
spec:
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: app
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prometeus
  selector:
    app: books
  clusterIP: 10.95.128.55
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack