#apiVersion: v1
#kind: Service
#metadata:
#  name: ratings
#spec:
#  clusterIP: 10.95.128.56
#  clusterIPs:
#    - 10.95.128.56
#  selector:
#    app: ratings
#  ports:
#    - protocol: TCP
#      port: 50052
#      targetPort: 8080
#      name: app
#    - protocol: TCP
#      port: 9090
#      targetPort: 9090
#      name: prometeus

kind: Service
apiVersion: v1
metadata:
  name: ratings
  namespace: default
  labels:
    app: ratings
spec:
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
      name: app
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prometeus
  selector:
    app: ratings
  clusterIP: 10.95.128.56
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack